alibaba/urls.py
from django.conf.urls import include , url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from quickstart import views
# Serializers define the API representation.
'''
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
'''
# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'products', views.ProductViewSet)
router.register(r'tables', views.TableViewSet)
router.register(r'notifs', views.NotifViewSet)
#router.register(r'notifs', views.AllNotifViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
	url(r'^', include('discover.urls') ),
	url(r'^shop/', include('shop.urls') ),
    url(r'^messenger/', include('messenger.urls') ),
    url(r'^authentication/', include('authentication.urls') ),
    url(r'^discover/', include('discover.urls') ),
    url(r'^notifications/', include('notifications.urls') ),
    url(r'^reactions/', include('reactions.urls') ),
    url(r'^collections/', include('collection.urls' , namespace="collections") ),
    url(r'^discounts/', include('discount.urls') ),
    url(r'^promote/', include('promote.urls') ),
    url(r'^admin/', admin.site.urls),
    url(r'^router/', include(router.urls)),
    url(r'^quickstart/', include('quickstart.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.conf.urls import url , include

from django.contrib import admin

from django.conf import settings

from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^register',views.register , name='register'),
	url(r'^login',views.login , name='login'),
    url(r'^logout',views.logout , name='logout'),
    url(r'^settings/$',views.settings , name='settings'),
    url(r'^settings/picture/$', views.picture, name='picture'),
    url(r'^settings/upload_picture/$', views.upload_picture,
        name='upload_picture'),
    url(r'^settings/password/$', views.password, name='password'),
    url(r'^settings/message/$', views.message, name='message'),
]

shop/urls.py
from django.conf.urls import url , include

from django.contrib import admin

from django.conf import settings

from django.conf.urls.static import static

from . import views

urlpatterns = [

	url(r'^products/$', views.products , name='products' ),
	url(r'^tables/$',views.tablesView , name='tables'),
	url(r'^wishlist',views.wishlist , name='wishlist'),
	url(r'^details/(?P<id>\w{0,50})/$',views.details),
	url(r'^view/(?P<id>\w{0,50})/$',views.view),
	url(r'^view/(?P<id>\w{0,50})/(?P<idP>\w{0,50})/$',views.view),
	url(r'^tablesAlbum/(?P<id>\w{0,50})/$',views.tablesAlbum),
	url(r'^details/(?P<id>\w{0,50})/page=(?P<idP>\w{0,50})/$',views.details),
	url(r'^album/(?P<id>\w{0,50})/$',views.album),
	url(r'^activateProduct/(?P<id>\w{0,50})/$',views.activateProduct),
	url(r'^addTableImage/(?P<id>\w{0,50})/$',views.addTableImage,name="addTableImage"),
	url(r'^addProductMainImage/(?P<id>\w{0,50})/$',views.addProductMainImage,name="addProductMainImage"),
	url(r'^duplicateProduct/(?P<id>\w{0,50})/$',views.duplicateProduct,name="duplicateProduct"),
	url(r'^deleteTable/(?P<id>\w{0,50})/$',views.deleteTable),
	url(r'^deleteProduct/(?P<id>\w{0,50})/$',views.deleteProduct),
	url(r'^editProduct/(?P<id>\w{0,50})/$',views.editProduct,name="editProduct"),
	url(r'^editTable/(?P<id>\w{0,50})/$',views.editTable,name="editTable"),
	url(r'^editProduct/(?P<id>\w{0,50})/$',views.editProduct,name="editProduct"),
	url(r'^addProduct/(?P<id>\w{0,50})/$',views.addProduct,name='addProduct'),
	url(r'^product_create/(?P<id>\w{0,50})/$',views.product_create,name='product_create'),
	url(r'^newTable',views.newTable, name='newTable'),
	url(r'^table_create/(?P<comment>[\w\-]+)/$',views.table_create , name='table_create'),
	url(r'^table_details/(?P<id>\w{0,50})/$',views.table_details , name='table_details'),

	url(r'^contact_create',views.contact_create , name='contact_create'),
	url(r'^product_details/(?P<id>\w{0,50})/$', views.product_details , name='product_details'),

]

authentication/models.py
from __future__ import unicode_literals

from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from shop.models import Product ,Table
from collection.models import Collection
# Create your models here.
def rename(instance,name):
	return instance.user.username.replace('@','_')+'/profile/'+str(instance.created_at)+name

class Activity(models.Model):
	user       = models.ForeignKey(User       ,default=1)  
	product    = models.ForeignKey(Product    ,null=True,related_name="visited_product"   )
	table      = models.ForeignKey(Table      ,null=True,related_name="visited_table"     )
	collection = models.ForeignKey(Collection ,null=True,related_name="visited_collection")
	created_at = models.DateTimeField(default=datetime.now,blank=True)
	def __str__(self):
		if self.product:
			return self.product.name
		elif self.table:
			return self.table.name
		else:
			return self.collection.name 

class Profile(models.Model):
	user              = models.OneToOneField(User,default=1)
	url               = models.CharField(max_length=50, null=True, blank=True)
	job_title         = models.CharField(max_length=50, null=True, blank=True)
	picture           = models.ImageField(null=True,upload_to=rename)
	created_at        = models.DateTimeField(default=datetime.now, blank=True)
	wishedProducts    = models.ManyToManyField(Product,blank=True,related_name="wished_products")
	wishedCollections = models.ManyToManyField(Collection,blank=True,related_name="wished_collections")
	location          = models.CharField(max_length=50, null=True, blank=True)
	message           = models.CharField(max_length=250, null=True, blank=True)
	history           = models.ManyToManyField(Activity,blank=True,related_name="history")
	balance           = models.IntegerField(null=True,default=0) 
	#solde = models.IntegerField
	def __str__ (self):
		return self.user.username

authentication/forms.py
from django import forms
from django.contrib.auth.models import User




class ProfileForm(forms.ModelForm):

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=30,
        required=False)
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=30,
        required=False)
    job_title = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50,
        required=False)
    email = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=75,
        required=False)
    url = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50,
        required=False)
    location = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50,
        required=False)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'job_title',
                  'email', 'url', 'location', ]



class ChangePasswordForm(forms.ModelForm):
    id = forms.CharField(widget=forms.HiddenInput())
    old_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="Old password",
        required=True)

    new_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="New password",
        required=True)
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="Confirm new password",
        required=True)

    class Meta:
        model = User
        fields = ['id', 'old_password', 'new_password', 'confirm_password']

    def clean(self):
        super(ChangePasswordForm, self).clean()
        old_password = self.cleaned_data.get('old_password')
        new_password = self.cleaned_data.get('new_password')
        confirm_password = self.cleaned_data.get('confirm_password')
        id = self.cleaned_data.get('id')
        user = User.objects.get(pk=id)
        if not user.check_password(old_password):
            self._errors['old_password'] = self.error_class([
                'Old password don\'t match'])
        if new_password and new_password != confirm_password:
            self._errors['new_password'] = self.error_class([
                'Passwords don\'t match'])
        return self.cleaned_data

authentication/views.py
from django.shortcuts import render , redirect
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login, logout as auth_logout , update_session_auth_hash
from django.contrib.auth.models import User
from authentication.forms import ProfileForm , ChangePasswordForm
from authentication.models import Profile
from django.http import HttpResponse, Http404
from discover.views import getRecs
# Create your views here.
def register(request):
    if (request.method == 'POST'):
        print("register function called from authentication ...")
        # uname = request.POST['uname']
        email = request.POST['email']
        # fname = request.POST['fname']
        # lname = request.POST['lname']
        password = request.POST['password']
        confirmPassword = request.POST['confirmPassword']

        if (password == confirmPassword):
            #print "password == confirmPassword"
            if (User.objects.filter(username=email).exists()):
                print("Error , acout alreasy exists")
            else:
                user = User.objects.create_user(username=email, password=password)
                user.save()
                profile = Profile(user=user)
                profile.save()
                user = authenticate(username=email, password=password)
                if user is not None:
                    if user.is_active:
                        auth_login(request, user)
                        return redirect('/discover')
                else:
                    return redirect('/authentication/login')
        else:
            print("password and confirmation password dont match !")
        return redirect('/authentication/login')


def login(request):
    if (request.method == 'POST'):
        print("login function from authentication called ..")
        email = request.POST['email']
        password = request.POST['password']

        user = authenticate(username=email, password=password)

        if user is not None:
            if user.is_active:
                auth_login(request, user)
                return redirect('/discover')
        else:
            return redirect('/authentication/login')

        return redirect('/discover')
    else:
        rec = getRecs()
        rec1 = rec[0]
        rec2 = rec[1]
        context = {
            'rec1':rec1,
            'rec2':rec2,
        }
        return render(request, 'login.html',context)

def settings(request):
    user = request.user
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        if first_name:
            user.first_name = first_name
        last_name = request.POST.get('last_name')
        if last_name:
            user.last_name = last_name
        job_title = request.POST.get('job_title')
        if job_title:
            user.profile.job_title = job_title
        email = request.POST.get('email')
        if email:
            user.email = email
        url = request.POST.get('url')
        if url:
            user.profile.url = url
        location = request.POST.get('location')
        if location:
            user.profile.location = location
        user.profile.save()
        user.save()
        return redirect('/authentication/settings/')

    else:
        form = ProfileForm(instance=user, initial={
            'job_title': user.profile.job_title,
            'url': user.profile.url,
            'location': user.profile.location
            })
    return render(request, 'authentication/settings.html', {'form': form})

def picture(request):
    uploaded_picture = False
    try:
        if request.GET.get('upload_picture') == 'uploaded':
            uploaded_picture = True

    except Exception:
        pass

    return render(request, 'authentication/picture.html',
                  {'uploaded_picture': uploaded_picture})


def upload_picture(request):
    try:
        profile_pictures = django_settings.MEDIA_ROOT + '/profile_picture/'
        if not os.path.exists(profile_pictures):
            os.makedirs(profile_pictures)
        f = request.FILES['picture']
        filename = profile_pictures + request.user.username + '_tmp.jpg'
        with open(filename, 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)
        im = Image.open(filename)
        width, height = im.size
        if width > 350:
            new_width = 350
            new_height = (height * 350) / width
            new_size = new_width, new_height
            im.thumbnail(new_size, Image.ANTIALIAS)
            im.save(filename)

        return redirect('/settings/picture/?upload_picture=uploaded')

    except Exception as e:
        print(e)
        return redirect('/settings/picture/')


def password(request):
    user = request.user
    if request.method == 'POST':
        new_password = request.POST.get('new_password')

        user.set_password(new_password)
        user.save()
        update_session_auth_hash(request, user)
        return redirect('/authentication/settings/password/')
    else:
        form = ChangePasswordForm(instance=user)
    return render(request, 'authentication/password.html',{'form':form})

def message(request):
    if(request.method == 'POST'):
        message = request.POST.get('message')
        print(str(message))
        request.user.profile.message = str(message)
        request.user.profile.save()
        return redirect('/authentication/settings/message/')
    else:
        message = ""
        if request.user.profile.message != None:
            message = str(request.user.profile.message)
        context = {
            'message':message
        }
        return render(request, 'authentication/message.html',context)

def logout(request):
    auth_logout(request)
    return redirect('/discover')

authentication/templates/authentication/message.html
{% extends 'messenger/base.html' %}
{% load i18n %}

{% block title %}{% trans 'Account Settings' %}{% endblock %}

{% block main %}
  <div class="page-header">
    <h1>{% trans 'Account Settings' %}</h1>
  </div>

  <div class="row" style="margin-top: 2em;">
    <div class="col-md-3">
      {% include 'authentication/partial_settings_menu.html' with active='message' %}
    </div>
    <div class="col-md-9">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <h3 style="margin-top: 0;margin-bottom:50px;">{% trans 'Change Welcoming Message' %}</h3>
      <form role="form" class="form-horizontal" method="post" action="{% url 'message' %}">
        {% csrf_token %}
          <div class="form-group">
            <label for="message" class="col-sm-3 control-label">message</label>
            <div class="col-sm-9">
              <input class="form-control" id="id_message" maxlength="250" name="message" type="text" value="{{message}}" />
            </div>
          </div>
        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-9">
            <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock main %}

authentication/templates/authentication/partial_settings_menu.html
{% load i18n %}
<div class="list-group">
  <a href="{% url 'settings' %}" class="list-group-item{% if active == 'profile' %} active{% endif %}">{% trans 'Profile' %}</a>
  <a href="{% url 'picture' %}" class="list-group-item{% if active == 'picture' %} active{% endif %}">{% trans 'Picture' %}</a>
  <a href="{% url 'password' %}" class="list-group-item{% if active == 'password' %} active{% endif %}">{% trans 'Password' %}</a>
  <a href="{% url 'message' %}" class="list-group-item{% if active == 'message' %} active{% endif %}">{% trans 'Message' %}</a>
</div>

authentication/templates/authentication/password.html
{% extends 'messenger/base.html' %}
{% load i18n %}

{% block title %}{% trans 'Account Settings' %}{% endblock %}

{% block main %}
  <div class="page-header">
    <h1>{% trans 'Account Settings' %}</h1>
  </div>
  <div class="row" style="margin-top: 2em">
    <div class="col-md-3">
      {% include 'authentication/partial_settings_menu.html' with active='password' %}
    </div>
    <div class="col-md-9">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <h3 style="margin-top: 0">{% trans 'Change Password' %}</h3>
      <form role="form" class="form-horizontal" method="post" action="{% url 'password' %}">
        {% csrf_token %}
        {{ form.id }}
        {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.label }}" class="col-sm-3 control-label">{{ field.label }}</label>
            <div class="col-sm-9">
              {{ field }}
              {% if field.help_text %}
                <span class="help-block">{{ field.help_text }}</span>
              {% endif %}
              {% for error in field.errors %}
                <label class="control-label">{{ error }}</label>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-9">
            <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock main %}

authentication/templates/authentication/picture.html
{% extends 'messenger/base.html' %}

{% load i18n static %}

{% block title %}{% trans 'Account Settings' %}{% endblock %}

{% block head %}
  <link href="{% static 'css/jquery.Jcrop.min.css' %}" rel="stylesheet">
  <script src="{% static 'js/jquery.Jcrop.min.js' %}"></script>
  <script src="{% static 'js/picture.js' %}"></script>
{% endblock head %}

{% block main %}
  <div class="page-header">
    <h1>{% trans 'Account Settings' %}</h1>
  </div>
  <div class="row" style="margin-top: 2em">
    <div class="col-md-3">
      {% include 'authentication/partial_settings_menu.html' with active='picture' %}
    </div>
    <div class="col-md-9">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <h3 style="margin-top: 0">{% trans 'Change Picture' %}</h3>
      <img src="/media/{{ user.profile.picture }}" style="width: 150px; border-radius: 5px; margin-bottom: 1em;">
      <form enctype="multipart/form-data" method="post" action="{% url 'upload_picture' %}" id="picture-upload-form">
        {% csrf_token %}
        <input type="file" name="picture" style="display: none">
        <button type="button" class="btn btn-default" id="btn-upload-picture">{% trans 'Upload new picture' %}</button>
      </form>

      {% if uploaded_picture %}
        <form method="post" action="{% url 'save_uploaded_picture' %}">
          {% csrf_token %}
          <div class="modal fade" id="modal-upload-picture">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h4 class="modal-title">{% trans 'Crop Picture' %}</h4>
                </div>
                <div class="modal-body">
                  <div class="selected-picture">
                    <p>{% trans 'Crop the profile picture and then click on the' %} <strong>{% trans 'Save Picture' %}</strong> {% trans 'button' %}</p>
                    <img src="{% get_media_prefix %}profile_pictures/{{ user.username }}_tmp.jpg?_={% now 'U' %}" id="crop-picture">
                    <input type="hidden" id="x" name="x" />
                    <input type="hidden" id="y" name="y" />
                    <input type="hidden" id="w" name="w" />
                    <input type="hidden" id="h" name="h" />
                  </div>
                  <script type="text/javascript">
                    $(function () {
                      $("#modal-upload-picture").modal();
                      window.history.pushState("", "", "/settings/picture/");
                    });
                  </script>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Close' %}</button>
                  <button type="submit" class="btn btn-primary">{% trans 'Save changes' %}</button>
                </div>
              </div>
            </div>
          </div>
        </form>
      {% endif %}
    </div>
  </div>
{% endblock main %}

authentication/templates/authentication/settings.html
{% extends 'messenger/base.html' %}
{% load i18n %}
{% get_available_languages as LANGUAGES %}
{% get_current_language as CURRENT_LANGUAGE %}

{% block title %}Account Settings{% endblock %}

{% block main %}
  <div class="page-header">
    <h1>{% trans 'Account Settings' %}</h1>
  </div>
  <div class="row" style="margin-top: 2em">
    <div class="col-md-3">
      {% include 'authentication/partial_settings_menu.html' with active='profile' %}
    </div>
    <div class="col-md-9">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <h3 style="margin-top: 0">{% trans 'Edit Profile' %}</h3>
      <form role="form" class="form-horizontal" method="post" action="{% url 'settings' %}">
        {% csrf_token %}
        {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.label }}" class="col-sm-2 control-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {{ field }}
              {% if field.help_text %}
                <span class="help-block">{{ field.help_text }}</span>
              {% endif %}
              {% for error in field.errors %}
                <label class="control-label">{{ error }}</label>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
        {% comment %}
        <div class="form-group">
          <label for="language" class="col-sm-2 control-label">Language</label>
          <div class="col-sm-10">
            <select id="language" name="language" class="form-control">
              {% for lang in LANGUAGES %}
                <option value="{{ lang.0 }}">{{ lang.1 }}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        {% endcomment %}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock main %}