alibaba/urls.py
from django.conf.urls import include , url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from quickstart import views
# Serializers define the API representation.
'''
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
'''
# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'products', views.ProductViewSet)
router.register(r'tables', views.TableViewSet)
router.register(r'notifs', views.NotifViewSet)
#router.register(r'notifs', views.AllNotifViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
	url(r'^', include('discover.urls') ),
	url(r'^shop/', include('shop.urls') ),
    url(r'^messenger/', include('messenger.urls') ),
    url(r'^authentication/', include('authentication.urls') ),
    url(r'^discover/', include('discover.urls') ),
    url(r'^notifications/', include('notifications.urls') ),
    url(r'^reactions/', include('reactions.urls') ),
    url(r'^collections/', include('collection.urls' , namespace="collections") ),
    url(r'^discounts/', include('discount.urls') ),
    url(r'^promote/', include('promote.urls') ),
    url(r'^admin/', admin.site.urls),
    url(r'^router/', include(router.urls)),
    url(r'^quickstart/', include('quickstart.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

collection/urls.py
from django.conf.urls import url , include

from django.contrib import admin

from django.conf import settings

from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^$', views.collection_all , name='collection_all' ),
    url(r'^newCollection/$', views.newCollection , name='newCollection' ),
    url(r'^mine/$', views.mineCollections , name='mineCollection' ),
    url(r'^deleteCollection/(?P<id>\w{0,50})/$', views.deleteCollection , name='deleteCollection' ),
    url(r'^view/(?P<id>\w{0,50})/$', views.viewCollections , name='viewCollection' ),
    url(r'^edit/(?P<id>\w{0,50})/$', views.editCollections , name='editCollection' ),
]

shop/urls.py
from django.conf.urls import url , include

from django.contrib import admin

from django.conf import settings

from django.conf.urls.static import static

from . import views

urlpatterns = [

	url(r'^products/$', views.products , name='products' ),
	url(r'^tables/$',views.tablesView , name='tables'),
	url(r'^wishlist',views.wishlist , name='wishlist'),
	url(r'^details/(?P<id>\w{0,50})/$',views.details),
	url(r'^view/(?P<id>\w{0,50})/$',views.view),
	url(r'^view/(?P<id>\w{0,50})/(?P<idP>\w{0,50})/$',views.view),
	url(r'^tablesAlbum/(?P<id>\w{0,50})/$',views.tablesAlbum),
	url(r'^details/(?P<id>\w{0,50})/page=(?P<idP>\w{0,50})/$',views.details),
	url(r'^album/(?P<id>\w{0,50})/$',views.album),
	url(r'^activateProduct/(?P<id>\w{0,50})/$',views.activateProduct),
	url(r'^addTableImage/(?P<id>\w{0,50})/$',views.addTableImage,name="addTableImage"),
	url(r'^addProductMainImage/(?P<id>\w{0,50})/$',views.addProductMainImage,name="addProductMainImage"),
	url(r'^duplicateProduct/(?P<id>\w{0,50})/$',views.duplicateProduct,name="duplicateProduct"),
	url(r'^deleteTable/(?P<id>\w{0,50})/$',views.deleteTable),
	url(r'^deleteProduct/(?P<id>\w{0,50})/$',views.deleteProduct),
	url(r'^editProduct/(?P<id>\w{0,50})/$',views.editProduct,name="editProduct"),
	url(r'^editTable/(?P<id>\w{0,50})/$',views.editTable,name="editTable"),
	url(r'^editProduct/(?P<id>\w{0,50})/$',views.editProduct,name="editProduct"),
	url(r'^addProduct/(?P<id>\w{0,50})/$',views.addProduct,name='addProduct'),
	url(r'^product_create/(?P<id>\w{0,50})/$',views.product_create,name='product_create'),
	url(r'^newTable',views.newTable, name='newTable'),
	url(r'^table_create/(?P<comment>[\w\-]+)/$',views.table_create , name='table_create'),
	url(r'^table_details/(?P<id>\w{0,50})/$',views.table_details , name='table_details'),

	url(r'^contact_create',views.contact_create , name='contact_create'),
	url(r'^product_details/(?P<id>\w{0,50})/$', views.product_details , name='product_details'),

]

collection/models.py
from __future__ import unicode_literals

from django.db import models
from datetime import datetime
from django.conf import  settings

# Create your models here.
def renameC(instance,name):
	return instance.user.username.replace('@','_')+'/collections/'+instance.name+'/'+str(instance.created_at)+name

class Collection(models.Model):
    user         = models.ForeignKey(settings.AUTH_USER_MODEL,default=1)
    name         = models.CharField(max_length=200)
    description  = models.TextField()
    image        = models.ImageField(null=True,upload_to=renameC)
    created_at   = models.DateTimeField(default=datetime.now, blank=True)
    products     = models.ManyToManyField('shop.Product',blank=True,related_name='collecstions_products')
    activationChoices = (
	    (None, "I do not know now"),
	    (True, "Yes I acknowledge this"),
	    (False, "No, I do not like this") )
    isActive     = models.NullBooleanField(choices = activationChoices,default=True)

    def __str__(self):
        return self.name

collection/views.py
from django.shortcuts import render , redirect , get_object_or_404
from django.http import HttpResponse, Http404
from .models import Collection
from shop.models import Product , Table
from authentication.models import Activity
from discover.views import getRecs

# Create your views here.

def collection_all(request):
    if not request.user.is_authenticated():
        raise Http404

    wishedCollections = request.user.profile.wishedCollections.all()

    ret = Collection.objects.filter(isActive=True)
    rec = getRecs()
    rec1 = rec[0]
    rec2 = rec[1]
    return render(request,'collection/collections.html',
        {'collections':ret,'wishedCollections':wishedCollections,'rec1':rec1,'rec2':rec2,})

def mineCollections(request):
    if not request.user.is_authenticated():
        raise Http404

    ret = Collection.objects.filter(user=request.user)
    rec = getRecs()
    rec1 = rec[0]
    rec2 = rec[1]
    return render(request,'collection/mesCollections.html',{'collections':ret,'rec1':rec1,'rec2':rec2})

def deleteCollection(request,id):
    #print str(id)
    Collection.objects.filter(id=id).delete()
    return redirect('/collections/mine/')

def viewCollections(request,id):
    collection = get_object_or_404(Collection,id=id)
    if request.user.is_authenticated():
        activity = Activity(user=request.user,collection=collection)
        activity.save()
    rec = getRecs()
    rec1 = rec[0]
    rec2 = rec[1]
    return render(request,'collection/viewCollection.html',{'collection':collection,'rec1':rec1,'rec2':rec2,})


def editCollections(request,id):
    if not request.user.is_authenticated():
        raise Http404

    if(request.method == 'POST'):
        name = request.POST.get('collectionName')
        description = request.POST.get('collectionDesc')
        image = request.FILES.get('collectionImageInput')
        #print(type(image))
        products = request.POST.get('relatedProducts') ;
        collection = get_object_or_404(Collection,id=str(id))
        collection.name = name
        collection.description = description
        if image:
            collection.image = image
        products = str(products)
        #print products
        products = products.split('&')
        #print products
        collection.save()
        for pr in collection.products.all():
            collection.products.remove(pr)

        for i in range(len(products) -1 ):
            pr = get_object_or_404(Product,id=str(products[i]))
            collection.products.add(pr)
        collection.save()
        return redirect('/collections')
    else:
        collection = get_object_or_404(Collection,id=id)
        ret = []
        for table in request.user.table_set.all():
            for pr in table.product_set.all():
                ret.append(pr)
        collectionProducts = []
        for pr in collection.products.all():
            collectionProducts.append(pr)

        #print(len(ret))
        rec = getRecs()
        rec1 = rec[0]
        rec2 = rec[1]
        context = {
            'rec1':rec1,
            'rec2':rec2,
            'collection':collection,
            'products':ret,
            'collectionProducts':collectionProducts,
        }
        return render(request,'collection/editCollection.html',context)

def newCollection(request):
    if not request.user.is_authenticated():
        raise Http404

    if(request.method=='POST'):
        name = request.POST.get('collectionName')
        description = request.POST.get('collectionDesc')
        image = request.FILES.get('collectionImageInput')
        print(type(image))
        products = request.POST.get('relatedProducts') ;
        collection = Collection(user=request.user,name=name,description=description,image=image)
        products = str(products)
        #print products
        products = products.split('&')
        #print products
        collection.save()
        for i in range(len(products) -1 ):
            pr = get_object_or_404(Product,id=str(products[i]))
            collection.products.add(pr)
        collection.save()
        return redirect('/collections')
    else:
        ret = []
        for table in request.user.table_set.all():
            for product in table.product_set.all():
                #print product.name
                ret.append(product)
        rec = getRecs()
        rec1 = rec[0]
        rec2 = rec[1]
        return render(request,'collection/newCollection.html',context={'products':ret,'rec1':rec1,'rec2':rec2})

collection/templates/collection/collections.html
{% include 'partials/header.html' %}

{% load static %}
<script type="text/javascript">
	function share(id){
		var left = (screen.width/2)-300
		var fbpopup = window.open("https://www.facebook.com/sharer/sharer.php?u=127.0.0.1:8000/collections/view/"+ id +"/" , "pop", "width=600, height=400, scrollbars=no,left=" + left + "");
	}
</script>
<center style="margin-top:30px;">
  <h4 style="margin-top:25px;">
    <a class="btn" href="/collections/newCollection/">Creer une nouvelle collection</a>
  </h4>
</center>

<div class="row">
<div class="span12" style="margin-top:50px;margin-left:90px;">
  {% for collection in collections %}
    <div class="span3" style="height:330px;margin-left:20px; margin-bottom:20px;border : 1px solid rgb(220,220,220) ;" csrf="{{csrf_token}}" collection-id="{{collection.id}}">
        <div style="overflow:hidden;width:100%;line-height:220px;height:220px;background-color:rgb(170,170,170);">
          {% if collection.image %}
          <img src="/media/{{collection.image}}" style="width:100%; vertical-align:middle;" alt="" />
          {% else %}
          <img src="/media/default.jpg" style="width:100%; vertical-align:middle;" alt="" />
          {% endif %}
        </div>
        <center>
          <h5>{{collection.name}}</h5>
          <h6>{{collection.description}}</h6>
        </center>

        <center>
          <div style="height:27px;width:200px;">
              {% if collection in wishedCollections %}
                <div style="cursor:pointer;text-decoration:none;float:left;" class="addCollectionToWishlist active" >
              {% else %}
                <div style="cursor:pointer;text-decoration:none;float:left;" class="addCollectionToWishlist" >
              {% endif %}
              </div>
                <div class="facebookShareLink" onclick="share({{product.id}});return false;" style="cursor:pointer;text-decoration:none;margin-left:20px;float:right;" title="partager"       >
                    <img src="{% static 'themes/images/share.png' %}" style="height:20px;" />
                </div>
                <a href="/collections/view/{{collection.id}}/" class="btn" >View</a>
                <a href="/collections/edit/{{collection.id}}/" class="btn" >Edit</a>
          </div>
        </center>

        <!--
        <center>
          <div style="height:27px;width:150px;">
            {% if collection in wishedCollections %}
              <div style="cursor:pointer;text-decoration:none;float:left;width:25px;height:25px;background-color:red;" class="addCollectionToWishList active" >
              </div>
            {% else %}
              <div style="cursor:pointer;text-decoration:none;float:left;width:25px;height:25px;background-color:grey;" class="addCollectionToWishList" >
              </div>
            {% endif %}
            <a href="/collections/view/{{collection.id}}/" class="btn" >View</a>
            <a href="/collections/edit/{{collection.id}}/" class="btn" >Edit</a>
          </div>
        </center>
        -->
    </div>
  {% endfor %}
</div>
</div>

{% include 'partials/footer.html' %}

collection/templates/collection/editCollection.html
{% include 'partials/header.html' %}

{% load static %}

<style>
#list-of-selected-products {
  height:450px;
  overflow:hidden;
  overflow-y:scroll;
}
</style>
<style type="text/css">
.box {
width: 80%;
margin: 0 auto;
background: rgba(255,255,255,0.2);
padding: 35px;
border: 2px solid #fff;
border-radius: 20px/50px;
background-clip: padding-box;
text-align: center;
}
.overlay {
position: fixed;
top: 0;
bottom: 0;
left: 0;
right: 0;
background: rgba(0, 0, 0, 0.7);
transition: opacity 500ms;
visibility: hidden;
opacity: 0;
}
.overlay:target {
visibility: visible;
opacity: 1;
}
.popup {
margin: 70px auto;
padding: 20px;
background: #fff;
border-radius: 5px;
width: 35%;
position: relative;
transition: all 1s ease-in-out;
}
.popup h2 {
margin-top: 0;
color: #333;
font-family: Tahoma, Arial, sans-serif;
}
.popup .close {
position: absolute;
top: 20px;
right: 30px;
transition: all 200ms;
font-size: 30px;
font-weight: bold;
text-decoration: none;
color: #333;
}
.popup .close:hover {
color: #06D85F;
}
.popup .content {
max-height: 30%;
overflow: auto;
}

@media screen and (max-width: 700px){
  .box{
    width: 70%;
  }
  .popup{
    width: 70%;
  }
}
.list-group-item {
    position: relative;
    display: block;
    padding: 10px 15px;
    margin-bottom: -1px;
    background-color: #fff;
    border: 1px solid #ddd;
    cursor:pointer;
}

.list-group-item a {
  text-decoration:none;
}
.list-group-item:hover{
  background-color: rgb(245,245,245);
}
.list-group-item.active {
  background-color:   #337ab7;
}
</style>
<div class="col-md-3">
<div id="popup1" class="overlay">
  <div class="popup">
    <h4>Ajouter des produits a votre collection.</h4>
    <a class="close" href="#">&times;</a>

    <input type="text" id="choose-list-search" style="width:97%;">
    <div class="list-group" id="list-of-selected-products">
      {% for product in products %}
        {% if product in collectionProducts %}
          <a class="list-group-item product active" product-id="{{product.id}}" product-name="{{product.name}}" style="text-decoration:none;">
        {% else %}
          <a class="list-group-item product" product-id="{{product.id}}" product-name="{{product.name}}" style="text-decoration:none;">
        {% endif %}
          <img src="/media/{{ product.get_image.img }}" class="conversation-portrait">
          {{product.name}}
        </a>
      {% endfor %}
    </div>

</div>
</div>
</div>


<div class="row">

    <div class="span12" style="border : 1px solid rgb(220,220,220) ; height:560px;margin-left:100px;background-color:rgb(240,240,240);margin-top:50px;margin-bottom:50px;">
      <h4 style="margin-left:30px; margin-bottom:20px;">Creer une nouvelle collection:</h4>
      <div class="span7" style="border : 1px solid rgb(220,220,220) ; height:490px; margin-left:30px; background-color:rgb(250,250,250);">
        <form id="form" method="post" action="{% url 'collections:editCollection' id=collection.id %}" style="margin-left:20px;margin-top:20px;" enctype="multipart/form-data">
          {% csrf_token %}
          <h5>Nom</h5>
          <input type="text" style="width:618px;" name="collectionName" id="nameId" value={{collection.name}}><br>
          <h5>Description</h5>
          <input type="text" style="width:618px; height:120px;" name="collectionDesc" id="descId" value="{{collection.description}}"><br>
          <input type="file" name="collectionImageInput" id="collectionImageInput" style="display:none;">

          <div style="margin-top:8px;">
            <a class="btn" href="#popup1"><strong>Produits</strong></a>
          </div>
          <div style="height:100px; border : 1px solid rgb(220,220,220) ; width:630px; margin-top:15px;">
          </div>
          <center>
            <button id="preSubmitButton" style="margin-top:15px;" class="btn">
              <strong>Creer</strong>
            </button>
          </center>
        </form>
      </div>
      <div class="span4" style="border : 1px solid rgb(220,220,220) ; height:490px; margin-left:30px; background-color:rgb(250,250,250);">
        <center>
          <h4 style="margin-bottom:20px;">L'image de la collection:</h4>

          <div style="width:270px;height:150px; overflow:hidden;border : 1px solid rgb(220,220,220) ;">
            {% if collection.image %}
            <img id="previewImage" src="/media/{{collection.image}}" style=" width:100%;">
            {% else %}
            <img id="previewImage" src="/media/default.jpg" style=" width:100%;">
            {% endif %}
          </div>

          <button id="uploadCollectionImage" style="margin-top:50px;" class="btn"><strong>Ajouter</strong></button>
        </center>
      </div>
    </div>

</div>
<script src="{% static 'js/collections.js' %}"></script>

{% include 'partials/footer.html' %}

collection/templates/collection/mesCollections.html
{% include 'partials/header.html' %}

{% load static %}
<style>
  table, tr, td {
    border: 2px solid black;
  }
  a {
    cursor:pointer;
  }
</style>
<center>
  <table style="margin-top:50px;">
    {% for collection in collections %}
    <tr style="background-color:rgb(245,245,245);border: 1px solid black;" collection-id="{{collection.id}}">
      <td><!-- image -->
        <div style="height:120px;line-height:120px;width:150px;overflow:hidden;background-color:rgb(220,220,220);">
          {% if collection.image %}
          <img src="/media/{{collection.image}}" style="width:150px;" />
          {% else %}
          <img src="/media/default.jpg" style="width:150px;" />
          {% endif %}
        </div>
      </td>
      <td><!-- nom -->
          <h5>{{collection.name}}</h5>
      </td>
      <td style="width:400px;">
        <h5>{{collection.description}}</h5>
      </td>
      <td style="width:80px;">
        <center>
          <a style="text-decoration:none;" href="/collections/edit/{{collection.id}}/"><h5>Modifier</h5></a>
        </center>
      </td>
      <td style="width:80px;">
        <center>
          <a style="text-decoration:none;" href="/collections/view/{{collection.id}}/"><h5>Voir</h5></a>
        </center>
      </td>
      <td style="width:80px;">
        <center>
          <a style="text-decoration:none;" onclick="deleteCollection({{collection.id}});return false;" ><h5>Supprimer</h5></a>
        </center>
      </td>
    </tr>
    {% endfor %}
  </table>
</center>

{% include 'partials/footer.html' %}

collection/templates/collection/newCollection.html
{% include 'partials/header.html' %}

{% load static %}
<style>
#list-of-selected-products {
  height:450px;
  overflow:hidden;
  overflow-y:scroll;
}
</style>
<style type="text/css">
.box {
width: 80%;
margin: 0 auto;
background: rgba(255,255,255,0.2);
padding: 35px;
border: 2px solid #fff;
border-radius: 20px/50px;
background-clip: padding-box;
text-align: center;
}
.overlay {
position: fixed;
top: 0;
bottom: 0;
left: 0;
right: 0;
background: rgba(0, 0, 0, 0.7);
transition: opacity 500ms;
visibility: hidden;
opacity: 0;
}
.overlay:target {
visibility: visible;
opacity: 1;
}
.popup {
margin: 70px auto;
padding: 20px;
background: #fff;
border-radius: 5px;
width: 35%;
position: relative;
transition: all 1s ease-in-out;
}
.popup h2 {
margin-top: 0;
color: #333;
font-family: Tahoma, Arial, sans-serif;
}
.popup .close {
position: absolute;
top: 20px;
right: 30px;
transition: all 200ms;
font-size: 30px;
font-weight: bold;
text-decoration: none;
color: #333;
}
.popup .close:hover {
color: #06D85F;
}
.popup .content {
max-height: 30%;
overflow: auto;
}

@media screen and (max-width: 700px){
  .box{
    width: 70%;
  }
  .popup{
    width: 70%;
  }
}
.list-group-item {
    position: relative;
    display: block;
    padding: 10px 15px;
    margin-bottom: -1px;
    background-color: #fff;
    border: 1px solid #ddd;
    cursor:pointer;
}

.list-group-item a {
  text-decoration:none;
}
.list-group-item:hover{
  background-color: rgb(245,245,245);
}
.list-group-item.active {
  background-color:   #337ab7;
}
</style>
<div class="col-md-3">
<div id="popup1" class="overlay">
  <div class="popup">
    <h4>Ajouter des produits a votre collection.</h4>
    <a class="close" href="#">&times;</a>

    <input type="text" id="choose-list-search" style="width:97%;">
    <div class="list-group" id="list-of-selected-products">
      {% for product in products %}
        <a class="list-group-item product" product-id="{{product.id}}" product-name="{{product.name}}" style="text-decoration:none;">
          <img src="/media/{{ product.get_image.img }}" class="conversation-portrait">
          {{product.name}}
        </a>
      {% endfor %}
    </div>

</div>
</div>
</div>


<div class="row">

    <div class="span12" style="border : 1px solid rgb(220,220,220) ; height:560px;margin-left:100px;background-color:rgb(240,240,240);margin-top:50px;margin-bottom:50px;">
      <h4 style="margin-left:30px; margin-bottom:20px;">Creer une nouvelle collection:</h4>
      <div class="span7" style="border : 1px solid rgb(220,220,220) ; height:490px; margin-left:30px; background-color:rgb(250,250,250);">
        <form id="form" method="post" action="{% url 'collections:newCollection' %}" style="margin-left:20px;margin-top:20px;" enctype="multipart/form-data">
          {% csrf_token %}
          <h5>Nom</h5>
          <input type="text" style="width:618px;" name="collectionName" id="nameId"><br>
          <h5>Description</h5>
          <input type="text" style="width:618px; height:120px;" name="collectionDesc" id="descId"><br>
          <input type="file" name="collectionImageInput" id="collectionImageInput" style="display:none;">

          <div style="margin-top:8px;">
            <a class="btn" href="#popup1">Produits</a>
          </div>
          <div style="height:100px; border : 1px solid rgb(220,220,220) ; width:630px; margin-top:15px;">
          </div>
          <center>
            <a id="preSubmitButton" style="margin-top:15px;" class="btn">
              <strong>Creer</strong>
            </a>
          </center>
        </form>
      </div>
      <div class="span4" style="border : 1px solid rgb(220,220,220) ; height:490px; margin-left:30px; background-color:rgb(250,250,250);">
        <center>
          <h4 style="margin-bottom:20px;">L'image de la collection:</h4>

          <div style="width:270px;height:150px; overflow:hidden;border : 1px solid rgb(220,220,220) ;">
            <img id="previewImage" src="/media/default.jpg" style=" width:100%;">
          </div>

          <button id="uploadCollectionImage" style="margin-top:50px;" class="btn">Ajouter</button>
        </center>
      </div>
    </div>

</div>
<script src="{% static 'js/collections.js' %}"></script>

{% include 'partials/footer.html' %}

collection/templates/collection/viewCollection.html
{% include 'partials/header.html' %}

{% load static %}
<div class="row" style="margin-left:40px;margin-top:50px;">
      <div class="span12" style="border : 1px solid rgb(220,220,220) ;height:300px; background-color:rgb(240,240,240);" >
        <div class="span4" style="border : 1px solid rgb(220,220,220) ;height:298px;line-height:300px;background-color:black;margin-left:0px;overflow:hidden;">
          {% if collection.image %}
            <img src="/media/{{collection.image}}" style="width:100%;vertical-align:middle;" />
          {% else %}
            <img src="/media/default.jpg" style="width:100%;vertical-align:middle;" />
          {% endif %}
        </div>
        <div class="span7" style="height:150px;">
          <h5>Nom:{{collection.name}}</h5>
          <h5>Date de creation:{{collection.created_at}}</h5>
          <h5>Description:{{collection.description}}</h5>
          <h5><strong>Produits:</strong></h5>
          <div style="border : 1px solid rgb(220,220,220) ;width:100%; height:160px;background-color:rgb(245,245,245);overflow:hidden;overflow-y:scroll;">
            <table style="margin-left:10px;width:100%;" >
            {% for product in collection.products.all %}
              <tr style="border : 1px solid rgb(220,220,220) ;">
                <td style="height:30px;width:50px;">
                  <img src="/media/{{product.get_image.img}}" style="height:30px;" />
                </td>
                <td>
                  <a href="/shop/product_details/{{product.id}}/" style="text-decoration:none;">
                    <h5 style="margin-left:10px;">{{product.name}}</h5>
                  </a>
                </td>
              </tr>
            {% endfor %}
            </table>
          </div>
        </div>
      </div>
</div>

{% include 'partials/footer.html' %}